from datetime import datetime

demo_loads = [
    {
        "load_id": 1001,
        "origin": "RIVERDALE, GA",
        "destination": "ATLANTA, GA", 
        "pickup_datetime": datetime(2025, 7, 8, 10, 0),
        "delivery_datetime": datetime(2025, 7, 8, 18, 0),
        "equipment_type": "Van",
        "loadboard_rate": 1500.0,
        "currency": "USD",
        "notes": "Electronics shipment - handle with care",
        "weight": 15000.0,
        "weight_unit": "lbs",
        "commodity_type": "Electronics",
        "num_of_pieces": 25,
        "miles": 35,
        "dimensions": "48x40x60",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1002,
        "origin": "CHICAGO, IL",
        "destination": "MILWAUKEE, WI",
        "pickup_datetime": datetime(2025, 7, 9, 8, 0),
        "delivery_datetime": datetime(2025, 7, 9, 14, 0),
        "equipment_type": "Flatbed",
        "loadboard_rate": 800.0,
        "currency": "USD",
        "notes": "Construction materials - tarps required",
        "weight": 25000.0,
        "weight_unit": "lbs",
        "commodity_type": "Construction Materials",
        "num_of_pieces": 10,
        "miles": 92,
        "dimensions": "48x102x8",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1003,
        "origin": "DALLAS, TX",
        "destination": "HOUSTON, TX",
        "pickup_datetime": datetime(2025, 7, 10, 12, 0),
        "delivery_datetime": datetime(2025, 7, 10, 20, 0),
        "equipment_type": "Reefer",
        "loadboard_rate": 1200.0,
        "currency": "USD",
        "notes": "Frozen goods - maintain -10°F",
        "weight": 20000.0,
        "weight_unit": "lbs",
        "commodity_type": "Frozen Food",
        "num_of_pieces": 100,
        "miles": 240,
        "dimensions": "48x40x72",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1004,
        "origin": "PHOENIX, AZ",
        "destination": "LAS VEGAS, NV",
        "pickup_datetime": datetime(2025, 7, 11, 6, 0),
        "delivery_datetime": datetime(2025, 7, 11, 16, 0),
        "equipment_type": "Van",
        "loadboard_rate": 900.0,
        "currency": "USD",
        "notes": "Retail merchandise - no hazmat",
        "weight": 18000.0,
        "weight_unit": "lbs",
        "commodity_type": "Retail Goods",
        "num_of_pieces": 45,
        "miles": 295,
        "dimensions": "48x40x65",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1005,
        "origin": "MIAMI, FL",
        "destination": "ORLANDO, FL",
        "pickup_datetime": datetime(2025, 7, 12, 9, 0),
        "delivery_datetime": datetime(2025, 7, 12, 15, 0),
        "equipment_type": "Van",
        "loadboard_rate": 750.0,
        "currency": "USD",
        "notes": "Pharmaceutical products - temperature controlled",
        "weight": 12000.0,
        "weight_unit": "lbs",
        "commodity_type": "Pharmaceuticals",
        "num_of_pieces": 30,
        "miles": 235,
        "dimensions": "48x40x55",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1006,
        "origin": "DENVER, CO",
        "destination": "SALT LAKE CITY, UT",
        "pickup_datetime": datetime(2025, 7, 13, 7, 0),
        "delivery_datetime": datetime(2025, 7, 13, 19, 0),
        "equipment_type": "Flatbed",
        "loadboard_rate": 1100.0,
        "currency": "USD",
        "notes": "Heavy machinery - crane required",
        "weight": 35000.0,
        "weight_unit": "lbs",
        "commodity_type": "Machinery",
        "num_of_pieces": 3,
        "miles": 338,
        "dimensions": "96x102x12",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1007,
        "origin": "SEATTLE, WA",
        "destination": "PORTLAND, OR",
        "pickup_datetime": datetime(2025, 7, 14, 11, 0),
        "delivery_datetime": datetime(2025, 7, 14, 17, 0),
        "equipment_type": "Reefer",
        "loadboard_rate": 650.0,
        "currency": "USD",
        "notes": "Fresh seafood - maintain 32°F",
        "weight": 16000.0,
        "weight_unit": "lbs",
        "commodity_type": "Fresh Food",
        "num_of_pieces": 80,
        "miles": 173,
        "dimensions": "48x40x68",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1008,
        "origin": "MEMPHIS, TN",
        "destination": "NASHVILLE, TN",
        "pickup_datetime": datetime(2025, 7, 15, 8, 30),
        "delivery_datetime": datetime(2025, 7, 15, 14, 30),
        "equipment_type": "Van",
        "loadboard_rate": 550.0,
        "currency": "USD",
        "notes": "Auto parts - fragile items",
        "weight": 8000.0,
        "weight_unit": "lbs",
        "commodity_type": "Auto Parts",
        "num_of_pieces": 150,
        "miles": 210,
        "dimensions": "48x40x50",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1009,
        "origin": "ALBUQUERQUE, NM",
        "destination": "EL PASO, TX",
        "pickup_datetime": datetime(2025, 7, 16, 13, 0),
        "delivery_datetime": datetime(2025, 7, 16, 19, 0),
        "equipment_type": "Van",
        "loadboard_rate": 480.0,
        "currency": "USD",
        "notes": "Textiles and clothing",
        "weight": 10000.0,
        "weight_unit": "lbs",
        "commodity_type": "Textiles",
        "num_of_pieces": 200,
        "miles": 267,
        "dimensions": "48x40x58",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1010,
        "origin": "BALTIMORE, MD",
        "destination": "PHILADELPHIA, PA",
        "pickup_datetime": datetime(2025, 7, 17, 10, 0),
        "delivery_datetime": datetime(2025, 7, 17, 16, 0),
        "equipment_type": "Flatbed",
        "loadboard_rate": 380.0,
        "currency": "USD",
        "notes": "Steel beams - secure properly",
        "weight": 40000.0,
        "weight_unit": "lbs",
        "commodity_type": "Steel",
        "num_of_pieces": 8,
        "miles": 101,
        "dimensions": "120x102x6",
        "dimensions_unit": "inches"
    },
    {
        "load_id": 1011,
        "origin": "ATLANTA, GA",
        "destination": "PHILADELPHIA, PA",
        "pickup_datetime": datetime(2025, 7, 17, 10, 0),
        "delivery_datetime": datetime(2025, 7, 18, 16, 0),
        "equipment_type": "Flatbed",
        "loadboard_rate": 1200.0,
        "currency": "USD",
        "notes": "Steel beams - secure properly",
        "weight": 40000.0,
        "weight_unit": "lbs",
        "commodity_type": "Steel",
        "num_of_pieces": 8,
        "miles": 450,
        "dimensions": "120x102x6",
        "dimensions_unit": "inches"
    }

]