version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-local
    hostname: metabase
    volumes:
      - ./metabase-data:/metabase-data
      - ./metabase-app:/shared-data  # Access to analytics.db
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_SITE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    networks:
      - metabase-network
    restart: unless-stopped
    env_file:
      - .env  # Load environment variables from main .env file

  sync-app:
    image: python:3.11-slim
    container_name: analytics-sync-app
    volumes:
      - ./metabase-app:/metabase-app
      - ./ssl:/ssl  # Mount SSL certificates if available
    working_dir: /metabase-app
    environment:
      - PYTHONPATH=/metabase-app
    ports:
      - "8001:8001"
    networks:
      - metabase-network
    restart: unless-stopped
    env_file:
      - .env  # Load environment variables from main .env file
    command: sh -c "pip install -r requirements.txt && uvicorn sync_app:app --host 0.0.0.0 --port 8001 --ssl-keyfile /ssl/key.pem --ssl-certfile /ssl/cert.pem"    
    depends_on:
      - metabase

networks:
  metabase-network:
    driver: bridge
