version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///loads_demo.db
      - FMCSA_API_KEY=${FMCSA_API_KEY}
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
